azure_status_page/ViewModels/MetersViewModel.cs
using System;
using System.Collections.Generic;
using azure_status_page.client.Models;
using azure_status_page.core.Models;

namespace azure_status_page.ViewModels
{
	public class MetersViewModel
	{
		public List<MeterDefinition> ClientSideMeters { get; set; } = new List<MeterDefinition>();

		public List<MeterDefinitionServerBased> StatusPageMeters { get; set; } = new List<MeterDefinitionServerBased>();
	}
}

azure_status_page/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using azure_status_page.core;

namespace azure_status_page.Controllers
{
	public class HomeController : Controller
	{
		private SiteExtensionConfigurationService configService = new SiteExtensionConfigurationService();
		private AzureWebJobInstaller webJobInstaller = new AzureWebJobInstaller("CheckMetersAndUpdateSite", Path.Combine(AzureEnvironmentService.SiteExtensionLocation, "App_Data", "WebJob"), AzureEnvironmentService.WebSiteLocation);

		private void PrepareViewBag()
		{
			// check if the webjob is installed 
			ViewBag.WebJobInstalled = webJobInstaller.IsWebJobInstalled();
		}

		[HttpGet]
		public ActionResult Index()
		{
			// load the configuration
			var config = configService.LoadConfiguration();

			// prepare our default view bag
			PrepareViewBag();

			// render the config
			return View(config);
		}

		[HttpPost]
		public ActionResult Index(MeterStorageConfigurationModel config)
		{
			// store the config
			configService.VerifyAndStoreConfiguration(config);

			// prepare our default view bag
			PrepareViewBag();

			// render the config
			return View(config);
		}

		[HttpPost]
		public ActionResult Install()
		{
			// install the webjob
			webJobInstaller.InstallOrUpdateWebJob();

			// render the config
			return RedirectToAction("Index");
		}

		[HttpPost]
		public ActionResult Generate()
		{
			// Trigger
			AzureWebJobShutdownService.Peek();

			// prepare our default view bag
			PrepareViewBag();

			// render the config
			return RedirectToAction("Index");
		}

	}
}

azure_status_page/Controllers/MetersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using azure_status_page.core;
using azure_status_page.core.Models;
using azure_status_page.core.Repositories;
using azure_status_page.ViewModels;

namespace azure_status_page.Controllers
{
    public class MetersController : Controller
    {		
		private SiteExtensionConfigurationService configService = new SiteExtensionConfigurationService();

		private MeterManagerEx initializeMeterManager()
		{
			// try to load the configruation 
			var config = configService.LoadConfiguration();

			// generate the repository
			var repository = new AzureTableMeterManagerExRepository(config.StorageKey, config.StorageSecret, config.StorageTableName);

			// instantiate the meter manager
			return new MeterManagerEx(repository);
		}

		[HttpGet]
        public ActionResult Index()
        {
			// instantiate the meter manager
			var meterManagerEx = initializeMeterManager();

			// build the view model
			var viewModel = new MetersViewModel();

			// get all the MeterDefinitions for the client side meters
			viewModel.ClientSideMeters = meterManagerEx.GetClientSideDefinitions();

			// get all Server Based MeterDefinitions
			viewModel.StatusPageMeters = meterManagerEx.GetServerBasedDefinitions();

			// render the view
			return View (viewModel);
        }

		[HttpGet]
		public ActionResult Add()
		{
			// create the model 
			var meterDefinition = new MeterDefinitionServerBased()
			{
				MeterId = Guid.NewGuid().ToString(),
				MeterType = client.Models.nMeterTypes.Heartbeat,
				MeterServerCheckType = "HTTP",
				MeterServerCheckInformation = String.Empty
			}; 

			return View("Add", meterDefinition);
		}

		[HttpPost]
		public ActionResult Add(MeterDefinitionServerBased model)
		{
			// instantiate the meter manager
			var meterManagerEx = initializeMeterManager();

			// store the meterdefinition to the settings 
			meterManagerEx.CreateOrUpdateServerSideDefinition(model);

			// trigger the webjib
			AzureWebJobShutdownService.Peek();

			// Render the meters
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(String Id, String CheckType) 
		{ 
			// instantiate the meter manager
			var meterManagerEx = initializeMeterManager();
			var meterDefinition = meterManagerEx.GetServerBasedDefinition(Id, CheckType);

			// show the dialog
			return View("Add", meterDefinition);
		}

		[HttpGet]
		public ActionResult Delete(String Id, String CheckType)
		{
			// instantiate the meter manager
			var meterManagerEx = initializeMeterManager();
			meterManagerEx.DeleteServerSideDefinition(Id, CheckType);

			// Render the meters
			return RedirectToAction("Index");
		}
	}
}

azure_status_page/Views/Home/Index.cshtml
@model azure_status_page.core.MeterStorageConfigurationModel

@{
    ViewBag.Title = "Azure Status Page Generator - Configuration";
}

<style>
	.checkbox{ margin-top: 10px !important; }
</style>

@if (!Model.Valid) {
<div class="alert alert-danger" role="alert">
	Please enter a valid storage account and fill out the customization options to generate a 
	valid configuration. Currently no status page will be generated!
</div>
}

@if (!ViewBag.WebJobInstalled && Model.Valid) {
<div class="alert alert-warning" role="alert">
	Azure Status Pages implements the recurring update via webjob. This webjob is currently not installed. 
	Please install the webjob to generate a status page<br/><br/>
	
	@using (Html.BeginForm("Install", "Home")) {
		<input type="submit" class="btn btn-success" value="Install or Update WebJob">
	}
</div>

}

@using(Html.BeginForm("Index", "Home", FormMethod.Post, new { @class="form-horizontal", role="form" })) {

	<fieldset>
		<legend>Style & Theming</legend>
	
		<div class="form-group">
    		@Html.LabelFor(m => m.Title, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.Title)
		    	@Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.Brand, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.Brand)
		    	@Html.EditorFor(m => m.Brand, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.FavIcon, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.FavIcon)
		    	@Html.EditorFor(m => m.FavIcon, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

	</fieldset>
	<fieldset>
		<legend>Storage Account Information</legend>

		<div class="form-group">
    		@Html.LabelFor(m => m.StorageKey, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.StorageKey)
		    	@Html.EditorFor(m => m.StorageKey, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.StorageSecret, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.StorageSecret)
		    	@Html.EditorFor(m => m.StorageSecret, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.StorageTableName, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.StorageTableName)
		    	@Html.EditorFor(m => m.StorageTableName, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>
	
	</fieldset>

	<fieldset>
		<legend>PushOver Integration</legend>


		<div class="form-group">
			@Html.LabelFor(m => m.PushOverEnabled, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">				
				@Html.CheckBoxFor(m => m.PushOverEnabled, new { @checked = "checked", @class = "checkbox" })
			</div>
		</div>
	
		<div class="form-group">
    		@Html.LabelFor(m => m.PushOverToken, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.PushOverToken)
		    	@Html.EditorFor(m => m.PushOverToken, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.PushOverUser, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.PushOverUser)
		    	@Html.EditorFor(m => m.PushOverUser, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>	
	</fieldset>

	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">      		
			<button type="submit" class="btn btn-primary">
    				<i class="fa fa-check"></i> Save Settings
			</button>
    	</div>
  	</div>  		
}

@section ActionsBar {
	<ul class="nav navbar-nav navbar-right">
	@if(Model.Valid) {
		<li style="margin-right: 10px;">
			@using (Html.BeginForm("Generate", "Home", new { @class="navbar-form" })) {
				<button type="submit" class="btn btn-success navbar-btn">
    				<i class="fa fa-globe"></i> Re-Generate Status Page
				</button>
			}
		</li>

		<li>
			@using (Html.BeginForm("Install", "Home", new { @class="navbar-form" })) {
				<button type="submit" class="btn btn-success navbar-btn">
    				<i class="fa fa-upload"></i> Re-Install WebJob
				</button>
			}
		</li>
	}

	</ul>
}

azure_status_page/Views/Meters/Add.cshtml
@model azure_status_page.core.Models.MeterDefinitionServerBased

@{
    ViewBag.Title = "Add Meter";
}


@using(Html.BeginForm("Add", "Meters", FormMethod.Post, new { @class="form-horizontal", role="form" })) {
	<h3>Add/Edit Status Page Meter</h3>

	<fieldset>
		<legend>General</legend>

		<div class="form-group">
    		@Html.LabelFor(m => m.MeterId, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.MeterId)
		    	@Html.EditorFor(m => m.MeterId, new { htmlAttributes = new { @class = "form-control", @readonly="readonly" } })
			</div>
		</div>
	
		<div class="form-group">
    		@Html.LabelFor(m => m.MeterName, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.MeterName)
		    	@Html.EditorFor(m => m.MeterName, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.MeterCategory, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.MeterCategory)
		    	@Html.EditorFor(m => m.MeterCategory, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.MeterDisplayOrder, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.MeterDisplayOrder)
		    	@Html.EditorFor(m => m.MeterDisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

	</fieldset>

	<fieldset>
		<legend>URL to check</legend>
	
		<div class="form-group">
    		@Html.LabelFor(m => m.MeterServerCheckInformation, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.MeterServerCheckInformation)
		    	@Html.EditorFor(m => m.MeterServerCheckInformation, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.MeterValue, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.MeterValue)
		    	@Html.EditorFor(m => m.MeterValue, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

		<div class="form-group">
    		@Html.LabelFor(m => m.MeterServerCheckInterval, new { @class = "col-sm-2 control-label" })
			<div class="col-sm-10">
		    	@Html.ValidationMessageFor(m => m.MeterServerCheckInterval)
		    	@Html.EditorFor(m => m.MeterServerCheckInterval, new { htmlAttributes = new { @class = "form-control" } })
			</div>
		</div>

	</fieldset>

	@Html.HiddenFor(m => m.MeterId, new { id = "MeterId" })
	@Html.HiddenFor(m => m.MeterType, new { id = "MeterType" })
	@Html.HiddenFor(m => m.MeterServerCheckType, new { id = "MeterServerCheckType" })

	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">      		
			<button type="submit" class="btn btn-primary">
    				<i class="fa fa-check"></i> Save Meter
			</button>
    	</div>
  	</div>  		
}

azure_status_page/Views/Meters/Index.cshtml
@model azure_status_page.ViewModels.MetersViewModel

@{
    ViewBag.Title = "Meters";
}

<legend>Client Side Meters</legend>
@if (Model.ClientSideMeters.Count == 0) {
	<div class="bs-callout bs-callout-info"> 	
		<h4>No Meters are defined or no client posted data</h4> 
		<p>
		Client side Meters are information delivered from the services as self, e.g. a heartbeat or some complex 
		technical checks from time to time. This meters will be shown automatically in the status page. To integrate 
		client side meters check our Status Page SDKs here:
		</p>
		<ul>
			<li>.NET SDK for Client Side Meters - <a href="https://www.nuget.org/packages/statuspageclient/" target="_new">Visit nuget.org</a></li>
			<li>nodejs SDK for Client Side Meters - <a href="https://www.npmjs.com/package/azure-status-page-client" target="_new">Visit npmjs.com</a></li>
		</ul>
		<p>As soon your client is posting data the first time client side meters will be visible here!</p>	
	</div>
} else {
	<table class="table table-bordered">
		<tr>
			<th>MeterId</th>
			<th>Name</th>
			<th>Category</th>
			<th>Type</th>
			<th>Value</th>
		</tr>
		@foreach(var item in Model.ClientSideMeters)
		{
			<tr>
				<td>@item.MeterId</td>
				<td>@item.MeterName</td>
				<td>@item.MeterCategory</td>
				<td>@item.MeterType</td>
				<td>@item.MeterValue</td>
			</tr>
		}
	</table>
}

<legend>Status Page Meters (Server Based Meters)</legend>
<div class="bs-callout bs-callout-info"> 	
	<h4>Register Meters manually</h4> 
	<p>
	Status Page Meters are executed in the App Service the Status Page is hosted and can be used to check specific
	metrics from outside of the applicaton, e.g. the availability of a specific application
	</p>
</div>
<table class="table table-bordered">
	<tr>
		<th>MeterId</th>
		<th>Name</th>
		<th>Category</th>
		<th>Type</th>
		<th>Value</th>
		<th style="width: 100px; text-align: center; "><a href="@Url.Action("Add", "Meters")" class="btn btn-xs btn-primary"><i class="fa fa-plus"></i>&nbsp;Add</a></th>
	</tr>
	@foreach(var item in Model.StatusPageMeters)
	{
		<tr>
			<td>@item.MeterId</td>
			<td>@item.MeterName</td>
			<td>@item.MeterCategory</td>
			<td>@item.MeterType / @item.MeterServerCheckType</td>
			<td>@item.MeterValue</td>
			<td style="width: 100px; text-align: center; ">
				<a href="@Url.Action("Edit", "Meters", new { Id = @item.MeterId, CheckType = item.MeterServerCheckType })"  class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a>
				<a href="@Url.Action("Delete", "Meters", new { Id = @item.MeterId, CheckType = @item.MeterServerCheckType })" class="btn btn-xs btn-danger" onclick = "return confirm('Are you sure you wish to delete this meter?');"><i class="fa fa-trash"></i></a>
			</td>
		</tr>
	}	
</table>

azure_status_page/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- FontAwesome --> 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
		
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

	<!-- internal CSS -->
	<link rel="stylesheet" href="/content/bs-callout.css">
		
	<style>
		body { padding-top: 70px; }
	</style>		
  </head>
  <body>
	<nav class="navbar navbar-default navbar-fixed-top">
  		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
    		<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        			<span class="sr-only">Toggle navigation</span>
        			<span class="icon-bar"></span>
			        <span class="icon-bar"></span>
        			<span class="icon-bar"></span>
      			</button>
      			<a class="navbar-brand" href="/">
        			<img alt="Brand" src="https://raw.githubusercontent.com/dei79/azure-status-page/master/assets/icon-status-page-20x20.png">
      			</a>
				<a class="navbar-brand" href="/">Azure Status Page Generator</a>
  			</div>

 			<!-- Collect the nav links, forms, and other content for toggling -->
    		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i>&nbsp;Home</a></li>
					<li><a href="@Url.Action("Index", "Meters")"><i class="fa fa-tachometer"></i>&nbsp;Meters</a></li>
				</ul>		
				@RenderSection("ActionsBar", required: false)	      			
    		</div><!-- /.navbar-collapse -->				
		</div>
	</nav>	

	<div class="container">
    	@RenderBody()
	</div>				

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>